<a href="https://colab.research.google.com/github/armarmarm927/dl_lecture_competition_pub/blob/main/sparkproto16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.transforms as transforms
import torchvision.datasets as datasets
import torchvision.models as models
from torch.utils.data import DataLoader
from sklearn.metrics import confusion_matrix
import numpy as np
import matplotlib.pyplot as plt

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [25]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [26]:
transform_train = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.RandomAffine([-10,10],scale=(1,1.25)),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5)),
    transforms.RandomErasing(p=0.5,scale=(0.02,0.33),ratio=(0.3,3.3),value=0,inplace=False)
])

transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

In [27]:
train_dataset = datasets.CIFAR10(root='./data', train=True, download=True, transform=transform_train)
test_dataset = datasets.CIFAR10(root='./data', train=False, download=True, transform=transform_test)

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True, num_workers=4)
test_loader = DataLoader(test_dataset, batch_size=128, shuffle=False, num_workers=4)

In [28]:
model_ft = models.resnet50(pretrained=True)
model_ft.fc = nn.Linear(model_ft.fc.in_features, 10)
net = model_ft.to(device)

In [29]:
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(net.parameters(), lr=0.001)
scheduler = optim.lr_scheduler.StepLR(optimizer, step_size=10, gamma=0.1)

In [30]:
num_epochs = 50
loss_list = []
acc_list = []
train_acc_list = []

for epoch in range(num_epochs):
    net.train()
    correct_train = 0
    total_train = 0
    epoch_loss = 0

    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        epoch_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        correct_train += (predicted == labels).sum().item()
        total_train += labels.size(0)

    train_accuracy = 100. * correct_train / total_train
    train_acc_list.append(train_accuracy)
    print(f'Epoch {epoch+1}: Loss: {epoch_loss/len(train_loader):.4f}, Train Accuracy: {train_accuracy:.2f}%')
    loss_list.append(epoch_loss/len(train_loader))

    net.eval()
    correct = 0
    total = 0
    y_true = []
    y_pred = []

    with torch.no_grad():
        for inputs, labels in test_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = net(inputs)
            _, predicted = torch.max(outputs, 1)
            correct += (predicted == labels).sum().item()
            total += labels.size(0)
            y_true.extend(labels.cpu().numpy())
            y_pred.extend(predicted.cpu().numpy())

    test_accuracy = 100. * correct / total
    acc_list.append(test_accuracy)
    print(f'Test Accuracy: {test_accuracy:.2f}%')

    # 混同行列の出力
    cm = confusion_matrix(y_true, y_pred)
    print(f'Confusion Matrix (Epoch {epoch+1}):')
    print(cm)

    torch.save(net.state_dict(), '/content/drive/MyDrive/Weight_Epoch50.pth')
    scheduler.step()

Epoch 1: Loss: 1.1597, Train Accuracy: 60.15%
Test Accuracy: 72.86%
Confusion Matrix (Epoch 1):
[[845  19  23  14  13   6   6   2  60  12]
 [ 21 875   0   4   0  14   6   0  15  65]
 [104   7 536  28 110 126  66   9  10   4]
 [ 31  10  39 394  74 379  41  14   6  12]
 [ 41   3  25  20 809  57  22  20   3   0]
 [ 17   2  26  58  59 804   9  21   2   2]
 [  7   6  33  48  60  57 783   1   4   1]
 [ 61   2  15  19 140 134   9 606   2  12]
 [ 66  37   7  15   9   6   7   3 845   5]
 [ 64  77   3  10   1  15   5   4  32 789]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 2: Loss: 0.9996, Train Accuracy: 65.80%
Test Accuracy: 68.13%
Confusion Matrix (Epoch 2):
[[636  43  83  10   9   1   8   1 157  52]
 [ 17 906   4   4   0   6   5   0  22  36]
 [ 64  15 717  48  31  43  51   8  17   6]
 [ 41  17 116 585  22 112  59  15  27   6]
 [ 23   6 155 109 538  27  92  26  22   2]
 [ 22   9 126 189  26 585  17  13  12   1]
 [  9  21  80  81   7  10 783   2   7   0]
 [ 32   7  85 110  67  62  20 596   7  14]
 [ 39  72   6   7   5   4   4   1 847  15]
 [ 24 273   9  14   1  10  10   5  34 620]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 3: Loss: 0.9521, Train Accuracy: 67.66%
Test Accuracy: 76.70%
Confusion Matrix (Epoch 3):
[[771  32  42   6  11   2   4  10  96  26]
 [  6 885   5   1   0   4   3   1  30  65]
 [ 66   4 695  26  88  30  34  29  17  11]
 [ 17   5  98 561  56 150  42  32  24  15]
 [ 17   3  52  37 771  40  29  39  12   0]
 [  8   2  85 138  37 661  18  47   4   0]
 [  3   3  48  54  22  21 832   6   8   3]
 [ 21   5  32  36  41  39   2 807   4  13]
 [ 46  28  10   9   2   5   5   2 885   8]
 [ 26  90   6   9   1   6   2   8  50 802]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 4: Loss: 0.7616, Train Accuracy: 73.79%
Test Accuracy: 78.83%
Confusion Matrix (Epoch 4):
[[857  13  25  15   7   0   3   4  62  14]
 [ 17 920   7   1   0   3   0   1  25  26]
 [ 84   3 727  46  62  39  22  13   3   1]
 [ 23  12  52 701  53  98  28  17  11   5]
 [ 20   3  55  44 807  21  10  29   7   4]
 [ 15   5  38 180  38 680   9  32   3   0]
 [ 10  18  37  77  54  14 772   4  13   1]
 [ 33   3  28  67  42  46   0 772   3   6]
 [ 83  19   9   7   3   2   2   4 867   4]
 [ 37  97   8   9   0   7   3   5  54 780]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 5: Loss: 0.8401, Train Accuracy: 71.19%
Test Accuracy: 75.80%
Confusion Matrix (Epoch 5):
[[752  28  70  10  19   3  13  10  76  19]
 [  8 939   6  10   0   2   0   1  18  16]
 [ 64   6 672  36  60  40  85  22  15   0]
 [ 26   5 114 619  42 114  44  19  16   1]
 [ 14   2  79  41 725  30  50  47  12   0]
 [ 15   1  90 146  45 658  12  29   4   0]
 [  6   7  69  67  20  15 804   2  10   0]
 [ 18   7  51  35  25  41   4 813   2   4]
 [ 41  45  11  11   3   4   3   3 870   9]
 [ 26 155  13  16   1  11   5  13  32 728]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 6: Loss: 0.7158, Train Accuracy: 75.35%
Test Accuracy: 79.91%
Confusion Matrix (Epoch 6):
[[876  10  43   8   5   0   3   3  37  15]
 [ 16 917   6   2   1   1   3   1  19  34]
 [ 44   2 833  35  28   6  27  17   3   5]
 [ 34   7  78 687  39  48  71  19   7  10]
 [ 14   1 123  29 740   7  35  42   7   2]
 [ 19   1 119 218  40 512  38  48   1   4]
 [  9   6  50  31  11   2 887   3   1   0]
 [ 28   2  39  40  29  12   6 828   3  13]
 [ 57  15  15   9   1   0   5   2 887   9]
 [ 54  85   5   6   0   1   3   3  19 824]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 7: Loss: 0.6483, Train Accuracy: 77.52%
Test Accuracy: 80.56%
Confusion Matrix (Epoch 7):
[[826  10  37  15   5   2   4   0  92   9]
 [  7 913   8   5   1   8   5   0  38  15]
 [ 47   0 782  41  48  23  39  11   7   2]
 [ 20   1  81 686  30 106  50  14  11   1]
 [  9   0  84  44 780  25  40  10   8   0]
 [  7   0  67 141  34 713  15  16   7   0]
 [  4   3  35  35   3  13 897   4   6   0]
 [ 24   4  40  42  59  51   4 769   3   4]
 [ 19  13  19  13   3   2   0   0 929   2]
 [ 40 100  10   9   0  13   8   1  58 761]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 8: Loss: 0.6223, Train Accuracy: 78.48%
Test Accuracy: 80.15%
Confusion Matrix (Epoch 8):
[[862  20  15  21  15   0   6   6  27  28]
 [ 10 894   2   8   9   2   9   3   9  54]
 [ 64   2 606  69 101  49  81  10   5  13]
 [ 15   2  20 710  43 116  62   8   9  15]
 [  8   0  23  56 845   9  38  13   6   2]
 [  6   1  17 166  56 681  35  25   3  10]
 [  3   2   6  52  14   4 915   0   2   2]
 [ 10   1  14  59  69  35  11 780   1  20]
 [ 46  44   6  17   3   1   6   1 858  18]
 [ 17  75   1   8   6   5   7   4  13 864]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 9: Loss: 0.6860, Train Accuracy: 76.52%
Test Accuracy: 79.24%
Confusion Matrix (Epoch 9):
[[824  21  28   9   9   1   5   0  83  20]
 [  5 941   1   3   2   0   0   0  19  29]
 [ 58   7 660  53  98  24  62  12  22   4]
 [ 32  14  50 627  62  72  88  14  24  17]
 [ 26   2  29  22 835   7  31  33  13   2]
 [ 16   4  44 174  51 620  46  25  11   9]
 [  9   6  18  31  16   4 903   2  10   1]
 [ 28   2  30  55  46  23  10 792   7   7]
 [ 28  25   2   7   3   0   4   0 925   6]
 [ 29 125   3   3   0   0   6   2  35 797]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 10: Loss: 0.6041, Train Accuracy: 79.01%
Test Accuracy: 82.42%
Confusion Matrix (Epoch 10):
[[865   7  33   4  14   1   2   5  38  31]
 [  4 869   7   3   3   5   2   1  27  79]
 [ 39   2 796  36  42  39  19  17   8   2]
 [ 22   4  60 672  46  98  32  44  11  11]
 [  4   1  72  22 780  20  17  72   8   4]
 [  8   0  37 153  29 701   9  53   4   6]
 [ 12   2  42  41  19  14 857   7   2   4]
 [ 13   0  19  28  18  19   0 895   1   7]
 [ 39   9  10   5   3   1   3   1 920   9]
 [ 22  30   6   8   2   2   2   3  38 887]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 11: Loss: 0.4862, Train Accuracy: 83.08%
Test Accuracy: 85.31%
Confusion Matrix (Epoch 11):
[[881  12  26   6  10   0   5   2  42  16]
 [  6 937   2   3   0   2   0   1  12  37]
 [ 43   1 791  29  49  32  34  10   7   4]
 [ 20   6  46 668  37 143  36  29   8   7]
 [  6   1  33  23 845  23  28  33   6   2]
 [  6   0  28 108  27 784  12  28   5   2]
 [  6   3  21  32  10   9 913   2   4   0]
 [ 15   0  15  24  21  32   2 882   2   7]
 [ 28  14   3   5   4   2   0   0 935   9]
 [ 20  51   3   4   0   2   2   2  21 895]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 12: Loss: 0.4437, Train Accuracy: 84.48%
Test Accuracy: 85.57%
Confusion Matrix (Epoch 12):
[[886  10  26   5   6   1   3   5  43  15]
 [  6 938   4   4   1   1   1   1  11  33]
 [ 40   1 798  33  47  31  31  12   6   1]
 [ 18   5  42 714  37 115  25  28  10   6]
 [  7   1  36  30 857  18  18  26   5   2]
 [  4   0  28 141  29 757   7  29   5   0]
 [  5   3  24  41  11   7 903   2   4   0]
 [ 11   0  11  26  28  31   0 886   2   5]
 [ 36  12   3   4   5   1   0   1 931   7]
 [ 21  54   2   6   0   4   3   4  19 887]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 13: Loss: 0.4277, Train Accuracy: 85.08%
Test Accuracy: 85.95%
Confusion Matrix (Epoch 13):
[[880  10  26   8   7   1   4   1  48  15]
 [  6 934   3   3   0   2   1   0  15  36]
 [ 38   1 827  27  40  24  23  12   7   1]
 [ 19   6  43 709  31 126  28  25   8   5]
 [  7   1  45  27 850  17  25  21   6   1]
 [  5   0  35 122  27 771  10  24   5   1]
 [  5   3  27  32  11   7 908   1   5   1]
 [ 14   0  15  26  21  27   1 890   0   6]
 [ 29  11   3   5   5   2   0   1 934  10]
 [ 22  47   3   6   0   4   2   1  23 892]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 14: Loss: 0.4150, Train Accuracy: 85.58%
Test Accuracy: 86.16%
Confusion Matrix (Epoch 14):
[[900   9  23   6   9   1   3   3  33  13]
 [  6 939   1   5   0   3   1   1  15  29]
 [ 34   2 825  32  41  26  20  13   6   1]
 [ 17   3  40 719  34 127  26  20   8   6]
 [  7   1  40  32 848  20  20  28   4   0]
 [  4   0  34 118  24 782  11  23   3   1]
 [  5   3  30  36  12   7 897   4   5   1]
 [ 11   0  12  29  18  35   1 887   2   5]
 [ 34  10   5   6   3   3   0   0 929  10]
 [ 21  49   3   6   0   4   2   2  23 890]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 15: Loss: 0.3954, Train Accuracy: 86.19%
Test Accuracy: 86.21%
Confusion Matrix (Epoch 15):
[[904   9  19  11   6   0   3   4  30  14]
 [  6 944   1   5   1   2   1   0  12  28]
 [ 42   2 815  34  41  29  17  15   4   1]
 [ 13   4  39 740  29 116  22  25   9   3]
 [  5   1  35  38 843  21  22  30   5   0]
 [  5   0  23 131  17 781  13  27   3   0]
 [  6   3  28  46   9   9 889   4   4   2]
 [ 13   0  12  25  14  34   2 894   2   4]
 [ 38  12   5   7   4   2   0   0 925   7]
 [ 23  49   2   7   0   3   3   4  23 886]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 16: Loss: 0.3821, Train Accuracy: 86.52%
Test Accuracy: 86.37%
Confusion Matrix (Epoch 16):
[[887   9  26   7  10   1   4   4  40  12]
 [  5 943   2   5   1   3   2   0  15  24]
 [ 30   1 823  30  47  29  22  12   5   1]
 [ 15   4  37 706  37 137  28  24   7   5]
 [  4   1  32  27 866  19  20  26   5   0]
 [  4   0  21 114  25 799  11  21   4   1]
 [  5   3  24  30   9   8 913   3   3   2]
 [ 11   0   9  24  28  31   1 891   1   4]
 [ 32  11   6   7   3   4   0   0 931   6]
 [ 20  62   3   6   1   4   1   2  23 878]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 17: Loss: 0.3817, Train Accuracy: 86.66%
Test Accuracy: 86.57%
Confusion Matrix (Epoch 17):
[[908   9  17  10   5   0   3   2  31  15]
 [  6 949   1   5   0   4   0   0  11  24]
 [ 35   1 827  33  36  31  17  14   5   1]
 [ 15   3  40 711  30 136  27  26   7   5]
 [  6   1  39  35 849  18  20  26   6   0]
 [  5   0  23 101  21 813  10  23   2   2]
 [  5   2  31  39   7   6 900   3   4   3]
 [ 11   0  12  18  24  33   1 896   1   4]
 [ 37  14   5   5   3   3   0   0 921  12]
 [ 24  61   2   5   1   4   2   2  16 883]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 18: Loss: 0.3728, Train Accuracy: 86.87%
Test Accuracy: 86.79%
Confusion Matrix (Epoch 18):
[[905   9  22   6  11   0   4   3  25  15]
 [  7 950   1   6   0   0   0   0  11  25]
 [ 29   2 846  33  39  16  16  13   3   3]
 [ 15   4  37 747  35  97  26  27   6   6]
 [  5   1  43  28 860  13  19  27   4   0]
 [  5   0  27 136  25 766  12  25   3   1]
 [  5   4  31  42   9   6 893   3   4   3]
 [ 11   0  13  20  22  21   2 906   1   4]
 [ 39  12   5   6   4   4   0   0 922   8]
 [ 19  63   3   3   0   4   2   4  18 884]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 19: Loss: 0.3555, Train Accuracy: 87.52%
Test Accuracy: 86.42%
Confusion Matrix (Epoch 19):
[[892  10  23  11   7   1   3   2  36  15]
 [  5 936   1   3   0   5   3   0  15  32]
 [ 31   1 832  30  40  29  15  14   5   3]
 [ 15   3  40 719  30 150  18  18   5   2]
 [  6   1  38  30 856  23  14  26   6   0]
 [  4   0  25 109  20 806   7  26   1   2]
 [  5   2  27  51  12  11 883   5   1   3]
 [ 10   0  11  21  23  39   2 890   0   4]
 [ 28  10   7   7   4   3   0   0 932   9]
 [ 16  48   3   9   0   4   2   1  21 896]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 20: Loss: 0.3477, Train Accuracy: 87.87%
Test Accuracy: 86.60%
Confusion Matrix (Epoch 20):
[[897  10  22  11   9   1   3   2  30  15]
 [  2 949   1   5   0   4   1   0  13  25]
 [ 33   2 847  29  35  25  12  10   5   2]
 [ 15   3  38 725  33 127  31  18   5   5]
 [  5   1  43  28 850  18  20  30   5   0]
 [  6   0  25 125  20 783  13  22   5   1]
 [  5   2  28  37   9   7 904   3   2   3]
 [  9   0  14  22  24  31   1 893   1   5]
 [ 34  17   7   6   4   1   0   0 923   8]
 [ 23  59   2   3   0   4   2   1  17 889]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 21: Loss: 0.3323, Train Accuracy: 88.32%
Test Accuracy: 86.95%
Confusion Matrix (Epoch 21):
[[915   7  19   6   8   1   3   2  26  13]
 [  5 945   2   4   0   4   1   0  14  25]
 [ 33   1 847  30  39  21  14   9   5   1]
 [ 16   3  37 736  33 119  30  18   5   3]
 [  5   1  39  28 863  18  20  21   5   0]
 [  5   0  24 127  23 785  12  19   4   1]
 [  5   2  25  39  12   7 902   3   2   3]
 [ 12   0  12  22  26  33   2 888   1   4]
 [ 40  14   5   5   4   2   0   0 922   8]
 [ 24  54   3   4   0   4   2   1  16 892]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 22: Loss: 0.3222, Train Accuracy: 88.70%
Test Accuracy: 86.93%
Confusion Matrix (Epoch 22):
[[912   7  19   6   6   1   3   2  31  13]
 [  5 944   2   4   0   4   1   0  15  25]
 [ 36   1 847  29  35  24  14   8   5   1]
 [ 15   3  40 729  30 131  26  17   6   3]
 [  6   1  40  27 857  20  20  24   5   0]
 [  6   0  23 115  19 802  11  20   3   1]
 [  5   2  29  37  11   9 898   4   2   3]
 [ 13   0  12  23  23  36   2 886   1   4]
 [ 36  14   5   7   3   3   0   0 925   7]
 [ 24  50   3   5   0   3   2   2  18 893]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 23: Loss: 0.3216, Train Accuracy: 88.65%
Test Accuracy: 87.07%
Confusion Matrix (Epoch 23):
[[910   8  23   8   6   1   3   3  26  12]
 [  5 945   2   5   0   3   2   0  12  26]
 [ 34   1 846  34  36  20  15   9   4   1]
 [ 15   2  36 756  33 110  27  14   4   3]
 [  5   1  40  32 866  17  18  16   5   0]
 [  5   0  22 134  20 782  13  20   2   2]
 [  5   2  22  41  10   5 912   1   0   2]
 [ 11   0  14  26  25  36   2 882   0   4]
 [ 39  14   8   9   4   3   0   0 915   8]
 [ 24  53   3   8   0   3   2   1  13 893]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 24: Loss: 0.3258, Train Accuracy: 88.44%
Test Accuracy: 87.06%
Confusion Matrix (Epoch 24):
[[902   8  23   7   7   1   4   3  32  13]
 [  4 950   1   4   0   4   1   0  12  24]
 [ 33   2 842  30  38  22  14  13   5   1]
 [ 13   3  38 728  34 132  26  17   6   3]
 [  6   1  41  29 857  20  16  25   5   0]
 [  5   0  21 110  19 809  12  20   2   2]
 [  5   3  26  36  12   7 905   3   1   2]
 [ 11   0  11  20  25  33   2 894   0   4]
 [ 33  15   7   6   3   3   0   0 926   7]
 [ 23  54   3   4   0   3   2   2  16 893]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 25: Loss: 0.3193, Train Accuracy: 88.89%
Test Accuracy: 86.98%
Confusion Matrix (Epoch 25):
[[915   8  17   7   6   0   4   2  29  12]
 [  6 944   0   4   0   4   1   0  14  27]
 [ 40   2 834  35  36  23  13  11   5   1]
 [ 15   3  39 745  27 121  24  18   5   3]
 [  6   1  38  29 859  19  16  26   6   0]
 [  6   0  20 127  20 790  11  21   4   1]
 [  5   2  29  38  12   7 900   2   2   3]
 [ 15   0  12  21  25  33   2 888   0   4]
 [ 33  14   4   6   3   3   0   0 930   7]
 [ 26  53   2   4   0   3   2   1  16 893]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


Epoch 26: Loss: 0.3192, Train Accuracy: 88.85%
Test Accuracy: 87.11%
Confusion Matrix (Epoch 26):
[[906   8  20   9   8   0   4   3  30  12]
 [  6 942   1   4   0   3   1   1  14  28]
 [ 34   1 839  31  40  21  14  14   5   1]
 [ 14   3  38 739  34 120  25  18   5   4]
 [  5   1  36  29 865  19  16  24   5   0]
 [  5   0  21 117  21 802  10  20   3   1]
 [  5   2  26  40  13   7 901   2   1   3]
 [ 11   0  10  17  27  32   2 896   0   5]
 [ 37  13   5   7   3   4   0   0 923   8]
 [ 24  46   3   6   0   3   2   2  16 898]]


/usr/local/lib/python3.11/dist-packages/torch/utils/data/dataloader.py:624: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(


KeyboardInterrupt: 

In [ ]:
plt.plot(acc_list)
plt.title('Accuracy')
plt.xlabel('Epoch')
plt.xticks(np.arange(0,50,10))
plt.ylabel('Accuracy')
plt.show()

In [ ]:
plt.plot(train_acc_list)
plt.title('Training Accuracy')
plt.xlabel('Epoch')
plt.xticks(np.arange(0,50,10))
plt.ylabel('Accuracy')
plt.show()

In [ ]:
plt.plot(loss_list)
plt.title('Cross Entropy Loss')
plt.xlabel('Epoch')
plt.xticks(np.arange(0,50,10))
plt.ylabel('Accuracy')
plt.show()